version: '3.5'

services:

  web-app:
    image: web-app
    container_name: web-app
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - './app:/app'
    ports:
      - 5000:5000
    env_file:
      - ./.envs/develop/.flask
      - ./.envs/develop/.mysql
    depends_on:
      - web-db

  web-db:
    image: mysql:5.7
    container_name: web-db
    env_file:
      - .envs/develop/.mysql
    ports:
      - 3307:3306
